package kr.itsdev.devjobcollector.security.hardening;

public enum SecurityAuditEventType {
    COMPANY_CREATED,
    COMPANY_MEMBER_INVITED,
    COMPANY_MEMBER_ROLE_CHANGED,
    COMPANY_MEMBER_REMOVED,
    COMPANY_VERIFICATION_REQUESTED,
    COMPANY_VERIFICATION_APPROVED,
    COMPANY_VERIFICATION_REJECTED
}
